"""
DX Tooling: Visualize Chunks
Exports a debug_export.json for inspecting the semantic chunks generated by the ChunkingEngine.
Optionally draws bounding boxes on PDFs using PyMuPDF if installed.
"""

import json
import logging
from typing import List
from models.ldu import LogicalDocumentUnit

logger = logging.getLogger(__name__)

def export_debug_json(ldus: List[LogicalDocumentUnit], output_path: str = "debug_export.json") -> None:
    """Exports LDUs to a structured JSON for rapid tree inspection and verification."""
    data = []
    for ldu in ldus:
        # Convert Pydantic object to dict safely
        ldu_dict = ldu.model_dump()
        data.append(ldu_dict)
        
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        
    logger.info(f"Exported {len(ldus)} LDUs to {output_path}")

def draw_ldu_boxes(pdf_path: str, ldus: List[LogicalDocumentUnit], output_pdf_path: str) -> None:
    """
    Draws structural chunk boundaries over the source PDF.
    Requires PyMuPDF (fitz). Normalizes the [0,1] coordinates back to points.
    """
    try:
        import fitz  # PyMuPDF
    except ImportError:
        logger.warning("PyMuPDF (fitz) is required to draw boxes. Run `pip install pymupdf`. Falling back to JSON export only.")
        return
        
    doc = fitz.open(pdf_path)
    
    # Group LDUs by page
    page_ldus = {}
    for ldu in ldus:
        # LDUs can span multiple pages (e.g. lists/tables), we'll draw on the first matched page for simplicity
        if not ldu.page_refs:
            continue
        primary_page = ldu.page_refs[0] - 1  # fitz is 0-indexed, our refs are 1-indexed
        
        if primary_page not in page_ldus:
            page_ldus[primary_page] = []
        page_ldus[primary_page].append(ldu)
        
    # Draw boxes
    for page_num in range(len(doc)):
        if page_num not in page_ldus:
            continue
            
        page = doc[page_num]
        rect = page.rect
        width, height = rect.width, rect.height
        
        for idx, ldu in enumerate(page_ldus[page_num]):
            bbox = ldu.bounding_box
            # Denormalize [0, 1] to points
            x0 = bbox.x0 * width
            y0 = bbox.y0 * height
            x1 = bbox.x1 * width
            y1 = bbox.y1 * height
            
            fitz_rect = fitz.Rect(x0, y0, x1, y1)
            
            # Color code by chunk type
            color_map = {
                "header": (1, 0, 0),    # Red
                "text": (0, 0, 1),      # Blue
                "list": (0, 0.5, 0),    # Dark Green
                "table": (1, 0.5, 0),   # Orange
                "figure": (0.5, 0, 0.5) # Purple
            }
            color = color_map.get(ldu.chunk_type, (0, 0, 0))
            
            # Draw box
            page.draw_rect(fitz_rect, color=color, width=1.5)
            
            # Add small label at top left of box
            page.insert_text(fitz.Point(x0, max(0, y0 - 2)), f"{ldu.chunk_type} (Tokens: {ldu.token_count})", fontsize=6, color=color)
            
    doc.save(output_pdf_path)
    doc.close()
    logger.info(f"Visualized LDU boxes drawn to {output_pdf_path}")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger.info("visualize_chunks.py utility loaded. Import and pass LDUs to use.")
